name: Manual Echo Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to echo'
        required: true
        default: 'Hello, GitHub Actions!'

jobs:
  echo_job:
    runs-on: ubuntu-latest

    steps:
    - name: Echo a message
      run: echo "${{ github.event.inputs.message }}"
