name: DEV pipeline

on:

jobs:
  Podman_image_creation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current date and time
        run: date
        shell: bash

      - name: Deleted unknown images
        run: |
           echo "Execution from DEV branch"
        shell: bash
